name: First Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
     - name: Checkout Code
       uses: actions/checkout@v3

     - name: Run a sample Github action
       run: echo "This workflow run succesfully for this particular action"
     
      
    
    
